version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-mental_health_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    image: python:3.11-slim
    restart: unless-stopped
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    entrypoint: ["/app/scripts/run_migrations.sh"]
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - db
      - redis

volumes:
  db_data:
    driver: local
